myapp/chart/urls.py
from django.conf.urls import url
from . import views
app_name = 'chart'
urlpatterns =[
url(r'^$', views.index, name='index'),
url(r'^chart-room/(?P<channel_id>[0-9]+)/$', views.room, name='room'),
url(r'^category/(?P<channel_id>[0-9]+)/$', views.category, name='category'),
url(r'^chat/Help$', views.Help, name='Help'),
url(r'^thought$', views.thought, name='thought'),
]

myapp/myapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^chart/', include('chart.urls')),
    url(r'^admin/', admin.site.urls),
]

myapp/chart/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Channel(models.Model):
    channel_text = models.CharField(max_length=200)
    category = models.CharField(default='other',max_length=500)
    date_created = models.DateTimeField()
    def __str__(self):
        return self.channel_text
    

class Chat(models.Model):
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE)
    chat_text = models.CharField(max_length=1000)
    username = models.CharField(max_length=1000)
    date_chat = models.DateTimeField()
    def __str__(self):
        return self.chat_text

myapp/chart/forms.py
from django import forms
CHOICES = (("Job","Job",), ("Vacancy","Vacancy",), ("Hobies","Hobies",), ("Music","Music",),
        ("Movies","Movies",),( "Music_Video","Music_Video",), ("Politics","Politics",),
           ("Sports","Sports",),("Admission","Admission",),("others","others",))
class ChannelForm(forms.Form):
    channel=forms.CharField(label='Channel Name ', max_length=100)
    category=forms.CharField(label='Category', widget=forms.Select(choices=CHOICES))
    
class SearchForm(forms.Form):
    search=forms.CharField(label='Search Channnels',widget=forms.TextInput(attrs={'placeholder':'Type in keyword'}))
    
class ChatForm(forms.Form):
    message=forms.CharField(label='message',widget=forms.Textarea(attrs={'cols':'25','rows':'3'}))
    username=forms.CharField(label='username ',widget=forms.TextInput(attrs={'placeholder':'username','size':'24'}))

myapp/chart/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from .models import Channel, Chat
from .forms import *
from datetime import datetime
# Create your views here.
def index(request):
    clear_search= "";
    if request.method == 'POST':
        if "create_channel" in request.POST:  
          form = ChannelForm(request.POST);
          if form.is_valid():
            channel_name = form.cleaned_data['channel']
            category = form.cleaned_data['category']
            date = datetime.now()
            Channel.objects.create(channel_text=channel_name, date_created=date,category=category)
            channel = Channel.objects.all().order_by("-date_created");
        if "search_data" in request.POST:
            form2 = SearchForm(request.POST);
            if form2.is_valid():
              search=form2.cleaned_data["search"];
              channel = Channel.objects.filter(channel_text__icontains=search).order_by("-date_created");
              form = ChannelForm();
              clear_search= "**clear Search";
    else:
        form = ChannelForm();
        channel = Channel.objects.all().order_by("-date_created");
    categories = Channel.objects.all();
    cat=[];
    cat2=[];
    for category in categories:
        if category.category not in cat2:
           cat2.append(category.category);
           cat.append(category.id);
    form2 = SearchForm();
    context = {"channel":channel, "form": form, "form2":form2,"clear_search":clear_search, "cat":cat}
    return render(request, 'chart/index.html', context)
    
def room(request, channel_id):
    if request.method == 'POST':
       form=ChatForm(request.POST);
       if form.is_valid():
          message = form.cleaned_data['message']
          username = form.cleaned_data['username']
          date=datetime.now();
          Channel.objects.get(pk=channel_id).chat_set.create(chat_text=message,username=username,date_chat=date);
    channel = Channel.objects.get(pk=channel_id);
    form=ChatForm();
    context = {"channel":channel,"form":form,"channel_id":channel_id}
    return render(request, 'chart/chat.html', context)

def category(request, channel_id):
    channel = Channel.objects.get(pk=channel_id);
    channel = channel.category
    channel = Channel.objects.filter(category=channel).order_by("-date_created");
    form = ChannelForm();
    form2 = SearchForm();
    categories = Channel.objects.all();
    cat=[];
    cat2=[];
    for category in categories:
        if category.category not in cat2:
           cat2.append(category.category);
           cat.append(category.id);
    context = {"channel":channel, "form": form, "form2":form2, "cat":cat}
    return render(request, 'chart/index.html', context)


def Help(request):
    return render(request, 'chart/help.html')

def thought(request):
    return render(request, 'chart/thought.html')
    

myapp/chart/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  
  {% load static %}
  <link rel="stylesheet" href="{% static 'chart/bootstrap.min.css' %}">
  <script src="{% static 'chart/jquery.min.js' %}"></script>
  <script src="{% static 'chart/bootstrap.min.js' %}"></script>
  <script src="{% static 'chart/scroll.js' %}"></script>
  <link rel="stylesheet" href="{% static 'chart/styles.css' %}">
  
</head>

<body>

<div class="container-fluid">
<div class="row" style="background-color:black;">
<div class="col-xs-0 col-sm-1 col-md-1 col-lg-1">
   
   

   </div>
   <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
   {% load static %}
   <img src="{% static 'chart/01.jpg' %}" class="img-responsive" id="img" />

   </div>
   <div class="col-xs-0 col-sm-1 col-md-1 col-lg-1">
   
   

   </div>
   </div>
   </div>
<nav class="navbar navbar-inverse " id="navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">ChatApp</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'chart:index' %}">Home</a></li>
        <li><a href="{% url 'chart:thought' %}">My thought</a></li>
        <li><a href="{% url 'chart:Help' %}">Help</a></li>
      </ul>
    </div>
  </div>
</nav>

  <div class="container-fluid">
<div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'chart:index' %}">Home</a></li>
          <li><div class="butt"> <a href="#">Create new channel</a></div></li>
		  <li><div class="cancel"> <a href="#">Cancel channel</a></div></li>
		  {% for list in list %}
           <li> {{ list }}</li>
         {% endfor %}
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}
	  {% for list in list %}
{{ list }}
{% endfor %}
	  {% endblock %}
	 

	 
      </div>
    </div>

  </div>
</body>
</html>

myapp/chart/templates/chart/chat.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-8 ">
    <h1>room : <a href="{% url 'chart:room' channel_id %}#chat">{{ channel.channel_text }}</a></h1>
	<h2>{{ channel.chat_set.count }} Chats</h2>
    {% if channel %}
       {% for chanel in channel.chat_set.all %}
        <ul>
          <li>
		    <font color="lightseablue">
              <h5>Sent: {{ chanel.date_chat }}</h5>
	          <h5>@{{ chanel.username }}</h5>
			</font>
           <p>
	       {{ chanel.chat_text }}
	       </p>
         </li>
        </ul>
        <br>
       {% endfor%}
       <div id="chat" style="">
         <form action="{% url 'chart:room' channel_id %}#chat" method="post">
           {% csrf_token %}
           <table>
            {{ form.as_table }}
           </table>
           <input type="submit" value="send"/><br><br>
        </form>
        <br><br><br><br>
       </div>  
    {% endif %}
     </div>
       <div class="col-sm-4">
       </div>
   </div>
</div>
{% endblock %}

myapp/chart/templates/chart/help.html
{% extends "base.html" %}

{% block content %}

<h2>Guidlines</h2>
<ul>
<li>To create a channel or a chat room</li>
<li>Click on create channel link on <a href="{% url 'chart:index' %}">Home</a> or on side bar</li>
<li>Enter the channel name and select a category of your chat and press create</li>
<li>Your channel will appear in the <a href="{% url 'chart:index' %}">Home</a></li>
<li>If the category of your chat is empty before you create, it will appear on the top</li>
<li>You can click on  any these category to view all channel in that category</li>
<li>Enter any keyword of channel tittle to search channel</li>
<li>you can only chat/send message in each channel</li>
</ul>

{% endblock %}

myapp/chart/templates/chart/index.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
   <div class="row">
      <div class="col-sm-2">
	  Categories:
      </div>
      <div class="col-sm-10 ">
	  {% for chanel in channel %}
	    {% if chanel.id in cat %}
          <a href="{% url 'chart:category' chanel.id %}">{{ chanel.category }}</a>|
		{% endif %}
       {% endfor %}
      </div>
   </div>
</div>
<h1>My Chat Application</h1>
<form action="{% url 'chart:index' %}" method="post">
   {% csrf_token %}
     {{ form2 }} 
     <input type="submit" name="search_data" value="search" />
     <h3><a href="{% url 'chart:index' %}"><font color="red">{{ clear_search }}</font></a></h3>
</form>

<div class="butt"><h2> <a href="#">Create New Channel/Chatroom</a></h2></div>

<div class="channel" style="">
  <form action="{% url 'chart:index' %}" method="post">
    {% csrf_token %}
    <table>
       {{ form.as_table }}
    </table>
    <input type="submit" value="Create channel" name="create_channel"/><br><br>
    <input type="button" value="Cancel channel" class="cancel" />
   </form>
</div>
<h2>{{ channel.count}} Channels/Chat Room</h2>
 {% if channel %}
   {% for chanel in channel %}
   <ul>
     <li>
     <h3><a href="{% url 'chart:room' chanel.id %}#chat">{{ chanel.channel_text }}</a></h3>
	 <h4>Created : {{ chanel.date_created }}</h4>
     You can only <a href="{% url 'chart:room' chanel.id %}#chat">View/Chat</a> in the chat room
     </li>
   </ul>
   {% endfor%}
    <br><br><br><br> <br><br><br><br>
 {% endif %}
{% endblock %}

myapp/chart/templates/chart/thought.html
{% extends "base.html" %}

{% block content %}
<h4> My Thoughts</h4>
<ul>
<li>Since authentication is not required,</l> 
<li>each user during chat is required to enter their username on each chat </li>
<li>Message is sent on each channel</li>
<li>I have two model, Channel and Chat which have one to many database relationship</li>
<li>Each Channel can have many chat</li>
<li>All the templates extends to base templates</li>
<li>The app is responsive, can be used efficiently in mobile device</li>
</ul>
{% endblock %}